### ISSUE TITLE
Markdown best practices

### ISSUE THREAD

**Issue by arhimede** [dotkernel/.github#6]
in documentation how to , add :
- how to write links 
- how to write filenames
- one phrase per line
- and so on

**Comment by bidi47** [comment]
Don't use too many levels of heading: no more than 2-3 levels
    Use lists: helps readability
    Make links descriptive: not "click here" or "read more"
    Link to external resources: use full URL, not relative link
    Add a table of contents: easier to navigate content
    Use alt text for images: helps search engines and screen readers

above source
https://israelmitolu.hashnode.dev/markdown-for-technical-writers-tips-tricks-and-best-practices

details for Semantic Line Breaks (enhances 'one sentence per line') https://sembr.org/
GitHub Flavored Markdown Spec (full usage, few best practices) https://github.github.com/gfm/
